models:
  - name: fct_trips
    description: Fact table with all taxi trips including trip and payment details
    columns:
      - name: payment_type
        data_tests:
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
                quote: false